name: Build K3D Validate - DevContainer

on:
  push:
    branches:
      - main
    paths:
      - 'dind-k3d/**'
      - '.github/workflows/k3d-validate-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_ID }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push k3d-helmvalidate
        uses: docker/build-push-action@v4
        with:
          file: 'dind-k3d/Dockerfile'
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/retaildevcrews/k3d-helmvalidate:latest
